import Vue from "vue";
import {
    Avatar,
    Button,
    Layout,
    Table,
    Icon,
    Progress,
    Radio,
    Dropdown,
    Menu,
    Carousel,
    Input,
    Badge,
    Slider,
    Form,
    FormModel,
    Tooltip,
    Select,
    Switch,
    Tag,
    Spin,
    Alert,
    Checkbox,
    Tabs,
    Pagination,
    Comment,
    notification,
    Drawer,
    Cascader,
    Divider,
    Anchor,
    AutoComplete,
    BackTop,
    Collapse,
    Card,
    List,
    Popover,
    Tree,
    Timeline,
    Row,
    Col,
    Transfer,
    Modal,
    message,
    Popconfirm,
    Skeleton,
    ConfigProvider,
} from "ant-design-vue";

Vue.use(Skeleton);
Vue.use(Avatar);
Vue.use(Popconfirm);
Vue.use(Transfer);
Vue.use(Modal);
Vue.use(Divider);
Vue.use(Row);
Vue.use(Col);
Vue.use(Timeline);
Vue.use(Tree);
Vue.use(Popover);
Vue.use(List);
Vue.use(Card);
Vue.use(Button);
Vue.use(Layout);
Vue.use(Table);
Vue.use(Icon);
Vue.use(Progress);
Vue.use(Radio);
Vue.use(Dropdown);
Vue.use(Menu);
Vue.use(Carousel);
Vue.use(Input);
Vue.use(Badge);
Vue.use(Slider);
Vue.use(Form);
Vue.use(FormModel);
Vue.use(Tooltip);
Vue.use(Select);
Vue.use(Tag);
Vue.use(Spin);
Vue.use(Alert);
Vue.use(Checkbox);
Vue.use(Tabs);
Vue.use(Pagination);
Vue.use(Drawer);
Vue.use(Switch);
Vue.use(Cascader);
Vue.use(Anchor);
Vue.use(AutoComplete);
Vue.use(Collapse);
Vue.use(BackTop);
Vue.use(ConfigProvider);
Vue.use(Comment);

Vue.prototype.$notification = notification;
Vue.prototype.$message = message;
